[package]
name = "TME1"
version = "0.1.0"
authors = ["veyrack <veyrack.lin@etu.upmc.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
